
language: python
# cache: pip
matrix:
    include:
      - os: linux
        sudo: required
        python: 2.7
    
# branches:
#     only:
#         - develop
# git:
#     submodules: false
# services: 
#     - rabbitmq

before_install:
    - echo ====RODAN=====================================================
    - pwd
    - ls -al
    
    - sudo apt-get update -y
    - sudo apt-get install -y libpq-dev python-dev build-essential 
install: 
    # - pip install https://www.djangoproject.com/download/1.7.b4/tarball/
    - pip install psycopg2==2.5.5
    - pip install -r requirements.txt
before_script: 
    - mv rodan/settings.py.development rodan/settings.py
    - python manage.py makemigrations rodan
    - python manage.py migrate # --noinput
script: python manage.py test


notifications:
  email: false
