language: python
cache: pip
services: 
  - redis-server
  # - rabbitmq
# git:
#   submodules: false

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7

before_install:
  - echo Before_Install==========================================
  - pwd
  - ls -al
  - sudo apt-get update -qy

  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install -y postgresql-9.3 postgresql-contrib-9.3 postgresql-plpython-9.3
  - sudo pip install redis
  - sudo redis-server &
  # - sudo redis-server /etc/redis/redis.conf --port 6379
  # - sudo apt-get install -y postgresql-plpython-${PG_MAJOR}
  # - sudo apt-get install -y libpq-dev python-dev build-essential 
    
install: 
  - echo Install=================================================
  - pip install psycopg2==2.7.1
  # - pip install redis
  - pip install -r requirements.txt
    
before_script: 
  - echo Before_Script===========================================
  - mv rodan/settings.py.development rodan/settings.py
  - python manage.py makemigrations rodan
  - python manage.py migrate # --noinput
    
script: python manage.py test


notifications:
  email: false
