language: python
cache: pip
matrix:
    include:
      - os: linux
        sudo: required
        python: 2.7
    
# branches:
#     only:
#         - develop
# git:
#     submodules: false
# services: 
#     - rabbitmq
# python:
#     - "2.7"
before_install:
    - echo ==RODAN========================================
    - pwd
    - ls -al
    
    - sudo apt update
    - sudo apt install libpq-dev python-dev
install: 
    - pip install https://www.djangoproject.com/download/1.7.b4/tarball/
    - pip install -r requirements.txt
before_script: 
    # - mv rodan/settings_production.py.example rodan/settings_production.py
    # - python manage.py makemigrations rodan
    # - python manage.py syncdb --noinput
# script: python manage.py test
script: echo 'hello'

# notifications:
#   email:
#     recipients:
#       - ruth.berkow@mail.mcgill.ca
#     on_failure: change
