if: branch = master AND type IN (pull_request, cron) OR branch = develop OR branch = fix-travis-config
language: python
cache: pip
matrix:
  include:
  - os: linux
    sudo: required
    python: 2.7
services:
  - redis-server
  # - postgresql
before_install:
  # Python modules
  - pip install -r requirements.txt
  - export DJANGO_SECRET_KEY=local
  - sed -i 's/\/code\/Rodan\///g' ./rodan/settings.py
  - ./helper_scripts/install.sh
before_script:
  - python manage.py makemigrations rodan
  - python manage.py migrate
script:
  # - python manage.py test
notifications:
  email: false
  # slack:
    # secure: k4lwPAC7c0iSBOE1qI3RCwh8Le2ar/bLyUd1kw8YD+tM8MjZEevVAjTNOUjLBahgrrPLRtgrHI3pGNh8A/i5eixW9VyxA2k03U3CBKXobP6HidCChORPdPv6xcP01qns69Qdj7PmJzN5kcVYcMdIb6T1cIEorht4Z7XMWKgcpwA=
