language: python
cache: pip
services:
- redis-server
matrix:
  include:
  - os: linux
    sudo: required
    python: 2.7
before_install:
- echo before_install==========================================
- pwd
- ls -al
- sudo apt-get update -qy
- sudo /etc/init.d/postgresql stop
- sudo apt-get install -y postgresql-9.3 postgresql-contrib-9.3 postgresql-plpython-9.3
- sudo pip install redis
- sudo redis-server /etc/redis/redis.conf --port 6379
install:
- echo install=================================================
- pip install psycopg2==2.7.1
- pip install -r requirements.txt
before_script:
- echo before_script===========================================
- mv rodan/settings.py.development rodan/settings.py
- python manage.py makemigrations rodan
- python manage.py migrate
script: python manage.py test
notifications:
  email: false
  slack:
    secure: vX67ciffwUwl2JslPtdEIjc/UY5rsc66+iMnoiNGepG3uQAE9kH5Kk1CWfoV+oCT0Hx9+vacZA5lhpQPPHYAvJGpF01GEVmJGwOtoMMrtSZzCrFYmeHcf9KFu5Fz3MAEYb00wzUVqV+7p/Pc6l9nY5RdT8KYB3esIoEBgpUMXe8=
env:
  global:
    secure: LYfkhGgQUznhbCrTADYV/o+kJxTT0M3JIozjlldml1nm21PmCyTNOxp2isxByCd9moDOVaHDmpn2CGo2gHBLn3fD5ZY1E17fm5AkODZV7zomLqlsn2tmtcNkgmsVJ4hm7peuyG3I8S5Odr44UQQ8AM5KO9WSp9Trsk0Tjn+odu8=
